from pathlib import Path

import config

BLOCKED_PATTERNS = [
    r"rm\s+(-rf?|--recursive)?\s*[/~]$",
    r"rm\s+-rf?\s+\.$",
    r"rm\s+-rf?\s+/$",
    r"sudo\s+rm\s+-rf?\s+[/~]",
    r"mkfs\.",
    r"dd\s+if=.*/dev/",
    r":\s*\(\s*\)\s*\{",
    r">\s*/dev/sd",
    r"chmod\s+(-R\s+)?777\s+[/~]",
    r"wget.*\|\s*(ba)?sh",
    r"curl.*\|\s*(ba)?sh",
    r"eval\s*\$\(",
    r"base64\s+--decode.*\|\s*(ba)?sh",
    r"/etc/passwd",
    r"/etc/shadow",
    r"~/.ssh/id_",
    r"\.bash_history",
    r"\.zsh_history",
    r"gnome-keyring",
    r"kwallet",
    r">\s*/dev/null\s+2>&1\s*&\s*disown.*rm",
]

CRITICAL_PATTERNS = [
    (r"rm\s+(-[rfi]+\s+)?", "Remocao de arquivos"),
    (r"sudo\s+", "Execucao com privilegios elevados"),
    (r"docker\s+(rm|rmi|system\s+prune)", "Remocao de containers/imagens Docker"),
    (r"docker\s+run\s+.*--privileged", "Container privilegiado"),
    (r"mv\s+.+\s+/", "Mover arquivos para diretorio raiz"),
    (r"chmod\s+", "Alteracao de permissoes"),
    (r"chown\s+", "Alteracao de proprietario"),
    (r"kill\s+", "Encerrar processos"),
    (r"pkill\s+", "Encerrar processos por nome"),
    (r"killall\s+", "Encerrar todos os processos"),
    (r"systemctl\s+(stop|restart|disable)", "Gerenciamento de servicos"),
    (r"apt\s+(remove|purge|autoremove)", "Remocao de pacotes"),
    (r"pip\s+uninstall", "Remocao de pacotes Python"),
    (r"npm\s+uninstall", "Remocao de pacotes Node"),
    (r"git\s+push\s+.*--force", "Push forcado ao repositorio"),
    (r"git\s+reset\s+--hard", "Reset destrutivo do repositorio"),
    (r"git\s+clean\s+-fd", "Limpeza destrutiva do repositorio"),
    (r"truncate\s+", "Truncar arquivos"),
    (r"shred\s+", "Destruicao segura de arquivos"),
    (r"dd\s+", "Escrita direta em dispositivos"),
]

DANGEROUS_PATTERNS = [
    r"su\s+-",
    r"iptables",
    r"ufw\s+(disable|reset)",
    r"cp\s+.*\s+/bin",
    r"cp\s+.*\s+/usr",
    r"crontab\s+-r",
    r"visudo",
]

SAFE_COMMANDS = {
    "ls",
    "pwd",
    "cd",
    "cat",
    "head",
    "tail",
    "less",
    "more",
    "grep",
    "find",
    "wc",
    "sort",
    "uniq",
    "diff",
    "echo",
    "printf",
    "date",
    "cal",
    "uptime",
    "df",
    "du",
    "free",
    "top",
    "htop",
    "ps",
    "git",
    "python",
    "python3",
    "pip",
    "pip3",
    "node",
    "npm",
    "npx",
    "yarn",
    "cargo",
    "rustc",
    "go",
    "make",
    "cmake",
    "gcc",
    "g++",
    "tree",
    "file",
    "stat",
    "which",
    "whereis",
    "tar",
    "zip",
    "unzip",
    "gzip",
    "gunzip",
    "curl",
    "wget",
    "clear",
    "history",
    "nvim",
    "vim",
    "nano",
    "ollama",
    "nvidia-smi",
    "ruff",
    "pytest",
    "mypy",
    "black",
    "isort",
    "pre-commit",
}

SAFE_PATHS = {
    str(Path.home()),
    str(config.APP_DIR),
    "/tmp",
}

MAX_COMMAND_LENGTH = 1024
MAX_TIMEOUT = 120
DEFAULT_TIMEOUT = 30
