from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class IConsciencia(Protocol):
    def pensar(self, mensagem: str, contexto: dict | None = None) -> str: ...
    def get_context(self) -> dict: ...


@runtime_checkable
class IBoca(Protocol):
    def falar(self, texto: str, animacao: str | None = None) -> None: ...
    def is_speaking(self) -> bool: ...
    def stop(self) -> None: ...


@runtime_checkable
class IVisao(Protocol):
    def capturar(self) -> bytes | None: ...
    def analisar(self, imagem: bytes, prompt: str) -> str: ...


@runtime_checkable
class IAnimationController(Protocol):
    def set_animation(self, name: str) -> None: ...
    def get_current_animation(self) -> str: ...
    def reload_for_entity(self, entity_id: str) -> None: ...


@runtime_checkable
class IMemory(Protocol):
    def add(self, content: str, source: str = "user") -> str | None: ...
    def retrieve(self, query: str, max_chars: int = 600) -> str: ...
    def clear(self) -> None: ...


@runtime_checkable
class IEntityLoader(Protocol):
    entity_id: str

    def get_soul_prompt(self) -> str: ...
    def get_color_theme(self) -> dict[str, str]: ...
    def get_animation_path(self, name: str) -> str | None: ...
    def get_voice_reference(self) -> str | None: ...


@runtime_checkable
class IMetrics(Protocol):
    def record_time(self, name: str, elapsed: float) -> None: ...
    def record_success(self, name: str) -> None: ...
    def record_failure(self, name: str) -> None: ...
    def get_stats(self) -> dict[str, Any]: ...


@runtime_checkable
class IEventLogger(Protocol):
    def log_event(self, event_type: str, data: dict | None = None) -> None: ...
    def get_recent_events(self, limit: int = 10) -> list[dict]: ...
