NOMES_FEMININOS = {
    "maria",
    "ana",
    "julia",
    "beatriz",
    "laura",
    "luiza",
    "leticia",
    "amanda",
    "camila",
    "bruna",
    "fernanda",
    "gabriela",
    "isabela",
    "larissa",
    "mariana",
    "patricia",
    "rafaela",
    "tatiana",
    "vanessa",
    "vitoria",
    "carolina",
    "daniela",
    "eduarda",
    "fabiana",
    "giovana",
    "heloisa",
    "ingrid",
    "jessica",
    "karen",
    "luana",
    "milena",
    "natalia",
    "olivia",
    "paloma",
    "queila",
    "renata",
    "sabrina",
    "thais",
    "ursula",
    "viviane",
    "wanda",
    "ximena",
    "yasmin",
    "zelia",
    "alice",
    "sophia",
    "helena",
    "valentina",
    "aurora",
    "luna",
    "celia",
    "rosa",
    "clara",
    "lara",
    "livia",
    "isadora",
    "antonella",
    "emanuella",
    "lorena",
    "maya",
    "nina",
    "stella",
    "bianca",
    "elisa",
    "marina",
    "priscila",
    "simone",
}

NOMES_MASCULINOS = {
    "joao",
    "pedro",
    "lucas",
    "gabriel",
    "matheus",
    "felipe",
    "rafael",
    "gustavo",
    "bruno",
    "andre",
    "carlos",
    "daniel",
    "eduardo",
    "fabio",
    "guilherme",
    "henrique",
    "igor",
    "jonas",
    "kevin",
    "leonardo",
    "marcelo",
    "nicolas",
    "otavio",
    "paulo",
    "ricardo",
    "sergio",
    "thiago",
    "vinicius",
    "wagner",
    "xavier",
    "yuri",
    "diego",
    "arthur",
    "bernardo",
    "caio",
    "david",
    "enzo",
    "francisco",
    "heitor",
    "ian",
    "joaquim",
    "lorenzo",
    "miguel",
    "noah",
    "oliver",
    "pietro",
    "ravi",
    "samuel",
    "theo",
    "vicente",
    "william",
    "antonio",
    "jose",
    "luiz",
    "marcos",
    "roberto",
    "fernando",
    "rodrigo",
    "leandro",
    "murilo",
    "caique",
    "renan",
    "augusto",
}

NOMES_NEUTROS = {
    "alex",
    "ariel",
    "charlie",
    "chris",
    "claude",
    "dakota",
    "eden",
    "eli",
    "francis",
    "harper",
    "jamie",
    "jordan",
    "kelly",
    "kim",
    "leslie",
    "logan",
    "max",
    "morgan",
    "pat",
    "quinn",
    "reese",
    "riley",
    "sam",
    "sandy",
    "skyler",
    "taylor",
    "terry",
    "val",
    "robin",
    "rene",
    "dominique",
}

ORIGENS_CULTURAIS = {
    "portuguesa": ["joao", "maria", "pedro", "ana", "jose", "antonio", "manuel", "joaquim"],
    "italiana": ["giovanni", "giuseppe", "francesco", "antonio", "lorenzo", "enzo", "matteo", "luca"],
    "alema": ["hans", "fritz", "klaus", "heinrich", "wilhelm", "bruno", "otto", "karl"],
    "japonesa": ["yuki", "haruki", "kenji", "akira", "hiroshi", "takeshi", "yumi", "sakura"],
    "arabe": ["ahmed", "mohamed", "ali", "omar", "fatima", "aisha", "hassan", "hussein"],
    "hebraica": ["david", "daniel", "samuel", "gabriel", "rafael", "miguel", "isaias", "sara"],
    "grega": ["sofia", "helena", "theo", "nicolas", "alexandra", "dimitri", "stavros", "eleni"],
    "latina": ["julio", "cesar", "augusto", "marco", "paula", "claudia", "lucia", "aurora"],
    "inglesa": ["william", "james", "henry", "charles", "elizabeth", "victoria", "edward", "george"],
    "francesa": ["jean", "pierre", "louis", "marie", "claire", "rene", "dominique", "francois"],
    "espanhola": ["diego", "pablo", "santiago", "carmen", "lucia", "dolores", "rosario", "pilar"],
    "indigena": ["iara", "jurema", "ubirajara", "raoni", "taina", "moema", "jaci", "cauã"],
    "africana": ["kwame", "amara", "zuri", "jabari", "nia", "kofi", "ayanna", "malik"],
}

DIMINUTIVOS_COMUNS = {
    "andre": ["dre", "dedé", "andrezinho"],
    "gabriela": ["gabi", "gabizinha", "bela"],
    "rafael": ["rafa", "rafinha"],
    "fernanda": ["fer", "nanda", "fernandinha"],
    "vitoria": ["vic", "vivi", "toria", "vick"],
    "lucas": ["lu", "luca", "luquinha"],
    "beatriz": ["bia", "bibi", "bea"],
    "pedro": ["pedrinho", "pepeu"],
    "maria": ["mari", "mariah", "mah"],
}
